### PR TITLE
add dependency for magento 2.4

### PR DESCRIPTION
**Pull request by ioweb-gr**
For issue #18

### CODE REVIEW

**Comment by amenk** [comment]
Thank you!
Please do a short test if it is compatible, then I will merge.

**Comment by ioweb-gr** [comment]
It will take me a while before I can do the test though to prepare a staging env.

**Comment by mehdichaouch** [comment]
Any new about testing & merging this PR ?

**Comment by mehdichaouch** [comment]
I just tested in it in Magento 2.4.2 and it's works.

**Comment by amenk** [comment]
Thanks I will create a release later

**Comment by mehdichaouch** [comment]
Thank you.

**Pull request merged**
